### ISSUE TITLE
Month not being handled correctly in date picker

### ISSUE THREAD

**Issue by indently** [federicocotogno/Habit_Tracker_2020#2]
Hey guys, as you may know the month selector starts at the index of 0 for some reason, and I thought I solved that in my tutorial, but the other day I was using my app and apparently it was still doing the bug that when you pick on December, it selects November. That just means I did the indexing wrong (December = 11 still instead of 12).

I don't have time to fix this one, but it's good if you guys are aware.

**Comment by AnubhavPabby** [comment]
@federicocotogno Hi federicocotogno I am Anubhav Pabby I have worked on this issue and submitted a pull request to solve this bug.Please take a look at my pull request
